# Generated by Django 4.2.4 on 2023-11-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_Auth', '0002_remove_user_is_customer_user_department_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_academy_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_creatives_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_technology_head',
            field=models.BooleanField(default=False),
        ),
    ]
