# Generated by Django 4.2.4 on 2024-01-11 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
        ('U_Auth', '0003_user_is_academy_head_user_is_creatives_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.companies'),
        ),
    ]
