# Generated by Django 4.2.4 on 2023-11-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timesheet', '0002_time_sheet_client_time_sheet_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_sheet',
            name='Duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time_sheet',
            name='Location',
            field=models.CharField(choices=[('Work from Office', 'Work from Office'), ('Work from Home', 'Work from Home')], max_length=25),
        ),
    ]
