# Generated by Django 4.2.4 on 2024-01-14 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_initial'),
        ('Timesheet', '0003_time_sheet_duration_alter_time_sheet_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_sheet',
            name='Task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Tasks.task'),
            preserve_default=False,
        ),
    ]
