# Generated by Django 4.2.4 on 2024-01-14 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tasks', '0004_initial'),
        ('Timesheet', '0004_time_sheet_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_Date', models.DateField(null=True)),
                ('To_Date', models.DateField(null=True)),
                ('Status', models.CharField(default='Pending', max_length=50)),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tasks.task')),
            ],
        ),
    ]
