# Generated by Django 4.2.4 on 2024-01-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
        ('Timesheet', '0005_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='Client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clients.client'),
        ),
    ]
