# Generated by Django 4.2.4 on 2024-01-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timesheet', '0006_filter_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_sheet',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Reviced', 'Reviced')], default='Pending', max_length=100),
        ),
    ]
