# Generated by Django 4.2.4 on 2024-01-12 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Description', models.TextField()),
                ('Priority', models.CharField(choices=[('Normal', 'Normal'), ('Medium', 'Medium'), ('High', 'High')], default='Normal', max_length=50)),
                ('Start_Date', models.DateField(null=True)),
                ('Due_Date', models.DateField(null=True)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.client')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
