# Generated by Django 4.2.4 on 2024-01-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_remove_task_employee_task_added_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
